version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=changeme
          - POSTGRES_DB=moviesdb
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
